### ISSUE TITLE
cache: "no-store"  is not working

### ISSUE THREAD

**Issue by Siddh744542** [ClarityCoders/Ticket-Tutorial-App#5]
cache: "no-store"  is not working when i update the value andget redirected to the home route the values doesn't get updated untill i manually hard refresh the page

**Comment by Kubrianity** [comment]
@Siddh744542 Can you try putting router.push('/') before router.refresh() and run it again?

**Comment by Siddh744542** [comment]
@Kubrianity  thanks!!, it worked.

**Comment by ClarityCoders** [comment]
@Kubrianity Thanks for the assist.  router.refresh() will force the client cache to refresh and show changes. Otherwise it defaults to every 30 seconds I think?
